package com.orka.myfinances.ui.theme

import androidx.compose.ui.graphics.Color

// Light Colors (Monochrome Base)
val md_theme_light_primary = Color(0xFF000000)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E0E0)
val md_theme_light_onPrimaryContainer = Color(0xFF000000)
val md_theme_light_secondary = Color(0xFF005696) // Professional Deep Blue
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D35)
val md_theme_light_tertiary = Color(0xFF565F71) // Neutral Slate
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDAE2F9)
val md_theme_light_onTertiaryContainer = Color(0xFF131C2C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44474E)
val md_theme_light_outline = Color(0xFF74777F)

// Dark Colors (Monochrome Base)
val md_theme_dark_primary = Color(0xFFFFFFFF)
val md_theme_dark_onPrimary = Color(0xFF000000)
val md_theme_dark_primaryContainer = Color(0xFF333333)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_secondary = Color(0xFFA2C9FF)
val md_theme_dark_onSecondary = Color(0xFF003254)
val md_theme_dark_secondaryContainer = Color(0xFF00487E)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_tertiary = Color(0xFFBEC6DC)
val md_theme_dark_onTertiary = Color(0xFF283141)
val md_theme_dark_tertiaryContainer = Color(0xFF3E4759)
val md_theme_dark_onTertiaryContainer = Color(0xFFDAE2F9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF000000)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF000000)
val md_theme_dark_onSurface = Color(0xFFFFFFFF)
val md_theme_dark_surfaceVariant = Color(0xFF44474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val md_theme_dark_outline = Color(0xFF8E9199)
